Hotfix 13/modal updates
michealengland/react-debugging-demo pull request #18
Opened 2021-06-29 18:13 UTC by johnrobertmcc

Removed last line
updated class names
Refactored to be called from App, deleted Footer file

_Unsure how to add a close button without resetting the "completed" files. it opens based on the state_

2021-06-29 18:43 UTC, michealengland requested changes
Other than reverting a minor change, I'm am good with these changes as is.

2021-06-29 18:43 UTC, michealengland commented on .eslintrc
> +  "extends": ["plugin:react/recommended", "prettier"],
After testing this locally with the original rules `"eslint:recommended", "plugin:react/recommended", "prettier"`, I believe we should keep this as it originally was. Meanwhile, the `no-debugger` rule makes sense to move forward on as it's either on or off. There is no `warning` option for this feature that I could locate.

2021-06-29 20:33 UTC, johnrobertmcc commented
@michealengland eslint recommended readded

2021-06-30 12:06 UTC, michealengland approved these changes
👍

2021-06-30 12:06 UTC, merged